export const pokemonFilters = {
  type: [
    { id: 1, key: "Normal", value: "normal" },
    { id: 2, key: "Fire", value: "fire" },
    { id: 3, key: "Water", value: "water" },
    { id: 4, key: "Electric", value: "electric" },
    { id: 5, key: "Grass", value: "grass" },
    { id: 6, key: "Ice", value: "ice" },
    { id: 7, key: "Fighting", value: "fighting" },
    { id: 8, key: "Poison", value: "poison" },
    { id: 9, key: "Ground", value: "ground" },
    { id: 10, key: "Flying", value: "flying" },
    { id: 11, key: "Psychic", value: "psychic" },
    { id: 12, key: "Bug", value: "bug" },
    { id: 13, key: "Rock", value: "rock" },
    { id: 14, key: "Ghost", value: "ghost" },
    { id: 15, key: "Dragon", value: "dragon" },
    { id: 16, key: "Dark", value: "dark" },
    { id: 17, key: "Steel", value: "steel" },
    { id: 18, key: "Fairy", value: "fairy" },
  ],
  ability: [
    { id: 1, key: "Overgrow", value: "overgrow" },
    { id: 2, key: "Blaze", value: "blaze" },
    { id: 3, key: "Torrent", value: "torrent" },
    { id: 4, key: "Shield Dust", value: "shield dust" },
    { id: 5, key: "Keen Eye", value: "keen eye" },
    { id: 6, key: "Run Away", value: "run away" },
    { id: 7, key: "Intimidate", value: "intimidate" },
    { id: 8, key: "Levitate", value: "levitate" },
    { id: 9, key: "Static", value: "static" },
    { id: 10, key: "Synchronize", value: "synchronize" },
  ],
  region: [
    { id: 1, key: "Kanto", value: "kanto" },
    { id: 2, key: "Johto", value: "johto" },
    { id: 3, key: "Hoenn", value: "hoenn" },
    { id: 4, key: "Sinnoh", value: "sinnoh" },
    { id: 5, key: "Unova", value: "unova" },
    { id: 6, key: "Kalos", value: "kalos" },
    { id: 7, key: "Alola", value: "alola" },
    { id: 8, key: "Galar", value: "galar" },
    { id: 9, key: "Paldea", value: "paldea" },
  ],
  habitat: [
    { id: 1, key: "Cave", value: "cave" },
    { id: 2, key: "Forest", value: "forest" },
    { id: 3, key: "Grassland", value: "grassland" },
    { id: 4, key: "Mountain", value: "mountain" },
    { id: 5, key: "Rough Terrain", value: "rough terrain" },
    { id: 6, key: "Sea", value: "sea" },
    { id: 7, key: "Urban", value: "urban" },
    { id: 8, key: "Rare", value: "rare" },
  ],
  generation: [
    { id: 1, key: "Generation I", value: "generation-i" },
    { id: 2, key: "Generation II", value: "generation-ii" },
    { id: 3, key: "Generation III", value: "generation-iii" },
    { id: 4, key: "Generation IV", value: "generation-iv" },
    { id: 5, key: "Generation V", value: "generation-v" },
    { id: 6, key: "Generation VI", value: "generation-vi" },
    { id: 7, key: "Generation VII", value: "generation-vii" },
    { id: 8, key: "Generation VIII", value: "generation-viii" },
    { id: 9, key: "Generation IX", value: "generation-ix" },
  ],
  color: [
    { id: 1, key: "Red", value: "red" },
    { id: 2, key: "Blue", value: "blue" },
    { id: 3, key: "Green", value: "green" },
    { id: 4, key: "Purple", value: "purple" },
    { id: 5, key: "Pink", value: "pink" },
    { id: 6, key: "Brown", value: "brown" },
    { id: 7, key: "Gray", value: "gray" },
    { id: 8, key: "Black", value: "black" },
    { id: 9, key: "White", value: "white" },
    { id: 10, key: "Yellow", value: "yellow" },
  ],
  evolutionStage: [
    { id: 1, key: "Basic", value: "basic" },
    { id: 2, key: "Stage 1", value: "stage-1" },
    { id: 3, key: "Stage 2", value: "stage-2" },
  ],
  gender: [
    { id: 1, key: "Male", value: "male" },
    { id: 2, key: "Female", value: "female" },
    { id: 3, key: "Genderless", value: "genderless" },
  ],
  shape: [
    { id: 1, key: "Quadruped", value: "quadruped" },
    { id: 2, key: "Bipedal", value: "bipedal" },
    { id: 3, key: "Winged", value: "winged" },
    { id: 4, key: "Serpentine", value: "serpentine" },
    { id: 5, key: "Arms", value: "arms" },
    { id: 6, key: "Humanoid", value: "humanoid" },
    { id: 7, key: "Tentacled", value: "tentacled" },
    { id: 8, key: "Blob", value: "blob" },
    { id: 9, key: "Heads", value: "heads" },
    { id: 10, key: "Legs", value: "legs" },
  ],
  legendaryStatus: [
    { id: 1, key: "Legendary", value: "legendary" },
    { id: 2, key: "Mythical", value: "mythical" },
    { id: 3, key: "Regular", value: "regular" },
  ],
  gameVersion: [
    { id: 1, key: "Ruby", value: "ruby" },
    { id: 2, key: "Sapphire", value: "sapphire" },
    { id: 3, key: "Emerald", value: "emerald" },
    { id: 4, key: "Diamond", value: "diamond" },
    { id: 5, key: "Pearl", value: "pearl" },
    { id: 6, key: "Platinum", value: "platinum" },
    { id: 7, key: "Black", value: "black" },
    { id: 8, key: "White", value: "white" },
    { id: 9, key: "X", value: "x" },
    { id: 10, key: "Y", value: "y" },
    { id: 11, key: "Sun", value: "sun" },
    { id: 12, key: "Moon", value: "moon" },
    { id: 13, key: "Sword", value: "sword" },
    { id: 14, key: "Shield", value: "shield" },
    { id: 15, key: "Scarlet", value: "scarlet" },
    { id: 16, key: "Violet", value: "violet" },
  ],
};
