export default {
  bug: new URL("@/assets/typesIcons/bug.svg", import.meta.url).href,
  dark: new URL("@/assets/typesIcons/dark.svg", import.meta.url).href,
  dragon: new URL("@/assets/typesIcons/dragon.svg", import.meta.url).href,
  electric: new URL("@/assets/typesIcons/electric.svg", import.meta.url).href,
  fairy: new URL("@/assets/typesIcons/fairy.svg", import.meta.url).href,
  fighting: new URL("@/assets/typesIcons/fighting.svg", import.meta.url).href,
  fire: new URL("@/assets/typesIcons/fire.svg", import.meta.url).href,
  flying: new URL("@/assets/typesIcons/flying.svg", import.meta.url).href,
  ghost: new URL("@/assets/typesIcons/ghost.svg", import.meta.url).href,
  grass: new URL("@/assets/typesIcons/grass.svg", import.meta.url).href,
  ground: new URL("@/assets/typesIcons/ground.svg", import.meta.url).href,
  ice: new URL("@/assets/typesIcons/ice.svg", import.meta.url).href,
  normal: new URL("@/assets/typesIcons/normal.svg", import.meta.url).href,
  poison: new URL("@/assets/typesIcons/poison.svg", import.meta.url).href,
  psychic: new URL("@/assets/typesIcons/psychic.svg", import.meta.url).href,
  rock: new URL("@/assets/typesIcons/rock.svg", import.meta.url).href,
  steel: new URL("@/assets/typesIcons/steel.svg", import.meta.url).href,
  water: new URL("@/assets/typesIcons/water.svg", import.meta.url).href,
};
